from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import OrderViewSet, GenerateBillView, CreateLocalOrderView

# Create a router specifically for the orders app
router = DefaultRouter()
router.register(r'', OrderViewSet, basename='order')

urlpatterns = [
    # Include all the URLs generated by the router
    path('', include(router.urls)),
    path('<int:pk>/generate-bill/', GenerateBillView.as_view(), name='generate-bill'),
    path('create-local-order/', CreateLocalOrderView.as_view(), name='create-local-order'),

]