from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import OrderViewSet

# Create a router specifically for the orders app
router = DefaultRouter()
router.register(r'', OrderViewSet, basename='order')

urlpatterns = [
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]