# Generated by Django 5.1.6 on 2025-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_seller_groups_alter_seller_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
