# Generated by Django 5.1.6 on 2025-08-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, help_text='Variation of the product (e.g., Red XL, 250g)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price (defaults to price if blank)', max_digits=10, null=True)),
                ('total_stock', models.PositiveIntegerField(default=0, help_text='Total physical stock available (both offline and online).')),
                ('online_stock', models.PositiveIntegerField(default=0, help_text='Stock allocated for the online store.')),
                ('sale_type', models.CharField(choices=[('BOTH', 'Online & In-Store'), ('OFFLINE', 'In-Store Only'), ('ONLINE', 'Online Only')], default='BOTH', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Is the product available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('UPI', 'UPI Link'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('accepts_cod', models.BooleanField(default=False, help_text='Accept Cash on Delivery')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('tagline', models.CharField(blank=True, help_text='A short, catchy slogan for your store.', max_length=150, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Your business WhatsApp number for customer contact.', max_length=20, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Reason for the stock change', max_length=255, null=True)),
                ('action', models.CharField(choices=[('CREATED', 'Product Created'), ('UPDATED', 'Manual Update'), ('SALE', 'Sale'), ('RETURN', 'Return')], max_length=20)),
                ('change_total', models.IntegerField(help_text='Change in total stock (e.g., +10 or -2)')),
                ('change_online', models.IntegerField(help_text='Change in online stock (e.g., +5 or -1)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
