# Generated by Django 5.1.6 on 2025-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='accepts_cod',
            field=models.BooleanField(default=False, help_text='Accept Cash on Delivery'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('UPI', 'UPI Link'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
