# Generated by Django 5.1.6 on 2025-08-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='user_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='user_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='change_online',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='change_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
