# Generated by Django 5.1.6 on 2025-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeprofile_accepts_cod_storeprofile_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short, catchy slogan for your store.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Your business WhatsApp number for customer contact.', max_length=20, null=True),
        ),
    ]
