# Generated by Django 5.1.6 on 2025-08-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_stockhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='delivery_time_local',
            field=models.CharField(blank=True, help_text="Estimated delivery time for local orders (e.g., '2-3 days')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='delivery_time_national',
            field=models.CharField(blank=True, help_text="Estimated delivery time for out-of-state orders (e.g., '5-7 days')", max_length=50, null=True),
        ),
    ]
