# Generated by Django 5.1.6 on 2025-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock allocated for the online store. Cannot be more than total stock.'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='Total physical stock available (both offline and online).'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('online_stock__lte', models.F('total_stock'))), name='online_stock_lte_total_stock'),
        ),
    ]
