# Generated by Django 5.1.6 on 2025-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeprofile_delivery_time_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description for the shop page (max 255 chars).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the shop page (max 100 chars).', max_length=100, null=True),
        ),
    ]
