# Generated by Django 5.1.6 on 2025-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_stock_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, help_text='Variation of the product (e.g., Red XL, 250g)', max_length=100, null=True),
        ),
    ]
