# Generated by Django 5.1.6 on 2025-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='note',
            field=models.CharField(blank=True, help_text='Reason for the stock change', max_length=255, null=True),
        ),
    ]
