# Generated by Django 5.1.6 on 2025-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_stockhistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('BOTH', 'Online & In-Store'), ('OFFLINE', 'In-Store Only'), ('ONLINE', 'Online Only')], default='BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the product available for sale?'),
        ),
    ]
