# Generated by Django 5.1.6 on 2025-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_sender_message_sender_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_object_id',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_content_type',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
